### ISSUE TITLE
“btc_player_side” error after server admin use #restart command to restart the mission when side mission cycle enabled

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#657] opened 2019-04-01 18:19 UTC
**Arma 3 Version:** `1.90` (stable)
**Hearts and minds Version:** `1.19.2` (dev f4ae8d3)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```

**Description:**
Strange error shows up after server admin use #restart command to restart the mission.
I dont know what caused this, and it seems to have no effects on the missions. I just report the issue here in case.
![107410_20190402020412_1](https://user-images.githubusercontent.com/26923626/55349999-9bd63580-54ed-11e9-9bcb-1e3b7f201ad4.png)

**Steps to reproduce:**
- Login into the server hosting H&M by default.
- Use #restart command to restart the mission.
- Error pops up.

**Comment by GoldJohnKing** [comment] 2019-04-03 10:29
Sorry, I do not know what else information should be provided.
As I've mentioned, everytime server admin "#restart" the game on dedicated server, the error always shows up, though it seems to have no effect at all.
It always happens and has no relation to mods or something.

**Comment by Vdauphin** [comment] 2019-04-03 11:23
Hello,

> Sorry, I do not know what else information should be provided.

**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
**RHS USAF Version:** `0.x.x` (stable / dev + commit hash)
**Hearts and minds Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
```
**Add mission file:**
- Zip your .pbo mission file, drag and drop it here.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and server RPT file (you can also change the file extension to a .txt file and drag and drop it here). An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

> It always happens and has no relation to mods or something.

May be it looks obvious for you but it never happen to me, before and actually. It should to be related to something and still don't know what
An error can hide a previous one, so without RPT you can't know ()

Also, it looks like duplicate: https://github.com/Vdauphin/HeartsAndMinds/issues/641
But again, if none of us provide informations, nobody will be in position to resolve the issue

Cheers

**Comment by GoldJohnKing** [comment] 2019-04-03 13:59
Arma 3 Version: 1.90 (stable)
CBA Version:  3.10.1 (stable)
ACE3 Version: 3.12.6 (stable)
RHS USAF Version: 0.4.8 (stable)
Hearts and minds Version: 1.19.2 (dev f4ae8d3)

Mods:
- CBA_A3
- ace
- RHS USAF
- RHS AFRF
- TFAR Beta
- ...

Add mission file:
[SGLA_Hearts_and_Minds_RHSUS_LYTHIUM.lythium.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3038974/SGLA_Hearts_and_Minds_RHSUS_LYTHIUM.lythium.zip)

RPT log file:
This error seems not being logged into the RPT file.

Addition:
You shall see the error with this startup param on.
![屏幕截图(29)](https://user-images.githubusercontent.com/26923626/55484130-87637b80-565a-11e9-8c40-4635e457569c.png)

**Comment by Vdauphin** [comment] 2019-04-03 14:59
> This error seems not being logged into the RPT file.

All error, warning and other stuff are logged in the RPT. Please, upload server and client RPT

> You shall see the error with this startup param on.

No, if you have more than one because arma remove the previous error

**Comment by GoldJohnKing** [comment] 2019-04-03 16:56
Server side rpt is here, client's is still collecting.
[arma3server_x64_2019-04-04_00-45-06.zip](https://github.com/Vdauphin/HeartsAndMinds/files/3039840/arma3server_x64_2019-04-04_00-45-06.zip)

Please notice there're several mod loaded, so the rpt seems confusing, I'd try to host a clean server and reproduce the issue when I have plenty of time.

And the following error is caused by VCOM AI, not H&M, please ignore it:
>  0:49:36 Error in expression <then
{
_ammoC = configfile >> "CfgAmmo" >> _subAmmo;
};
>
>_actHit = getNumber (_a>
 0:49:36   Error position: <>> _subAmmo;
};
>
>_actHit = getNumber (_a>
> 0:49:36   Error >>: Type Config entry, expected String
> 0:49:36 File \vcomai\Vcom\Functions\FFE_Functions\fn_AutoConfig.sqf [RYD_fnc_AutoConfig], line 120

**Comment by Vdauphin** [comment] 2019-04-06 07:06
Hello,
Thanks to your mission file, I could reproduce the issue. This only append when you activate the mission side cycle parameter and you do a mission #restart
Cheers

**Closed** 2019-04-13 11:14 UTC
Labels: bug
