### ISSUE TITLE
[BUG] Random player gets setPos + Loadout of saved Data when another player joins the game

### ISSUE THREAD

**Issue by PulsarNeutronStar** [Vdauphin/HeartsAndMinds#1486] opened 2023-02-25 14:10 UTC
We noticed this behavior sporadically and we havent exactly figured out whats going on or how to reproduce the issue but here is what we observed so far:

Seemingly random player will be put to the location where player X has logged out before with player X kit.

Player A and B swapped slots (from medic to TL vise versa).
Player C got Player A Kit and Pos.

heres our respo
https://github.com/PulsarNeutronStar/HeartsAndMinds
currently based on 1.23.0

the only change on the core we did is 
ace_banana -> ACE_Humanitarian_Ration
"Oplitas" -> "Insurgents"
commenting out the BTC Arsenal actions on the btc_gear_object.

**Comment by Vdauphin** [comment] 2023-02-25 14:46
Hello,

Read this https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=75&tab=comments#comment-3469051

Also: https://github.com/Vdauphin/HeartsAndMinds/discussions/1485

Cheers

**Comment by PulsarNeutronStar** [comment] 2023-03-18 15:36
@Vdauphin if you want me to provide more information, reopen this issue and ask.

**Comment by Vdauphin** [comment] 2023-03-18 16:05
> If a Random person, which is actively playing and currently in a firefight gets teleported to a random location with a different kit when a further person joins the server and loads in is the intended behavior, i prefer not to use the feature.

This is not intended yes but as you describe it in the first place it sound like an intended behavior :

If Player A use the medic slot, when Player C will use the same medic slot after Player A left, player C will get kit and pos of player A when he was using medic slot

So please update the ticket with the template provided when you opened the issue. Without it, it is impossible to reproduce a bug

**Comment by PulsarNeutronStar** [comment] 2023-03-18 16:58
```
Player A and B swapped slots (from medic to TL vise versa).
Player C got Player A Kit and Pos.
```

Player C was jsut sitting on the server, doing nothing and simply playing the game. 
No switching of slots. nothing. Other players, A and B, switched slots.

**Comment by PulsarNeutronStar** [comment] 2023-03-18 17:01
This was 3 weeks ago, ill have to look if i still have the RPT. Same goes for missionfile.

**Comment by PulsarNeutronStar** [comment] 2023-03-18 18:06
And no, to my knowledge, no one of our guys used a cracked version of arma. We propagade mods via steam, upload our own mod to steam, use key verification, `kickduplicate = 1`and all that jazz.

And it has happend to myself, i ended up with the kit of someone else when they loaded in the game, and i am 100% Certain i have a legal version of the game. If you want i can show you the invoice for it.

**Comment by PulsarNeutronStar** [comment] 2023-03-18 18:57
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
**Hearts and minds Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
https://cdn.discordapp.com/attachments/1006511361804738580/1082367857066770582/Arma_3_Preset_CVO_HM_NorthTakistan.html
```

**Description:**
- A clear and concise description of what the bug is.

When a new player (A) joins the server and loads into the misison during a running mission,
a random player (C) that is currently connected to the server gets the loadout and position of the player (A) who just joined.


- Add a detailed description of the error. This makes it easier for us to fix the issue.
It is a very random occourance and it is hard to isolate or to create a reliable way to reproduce but we tested the following:
Running Session, no `#restart` or `#reassign`. Player Y and Player X decide to change slots (from Teamleader to Medic and vise versa).

They do that and a further Player Z suddenly recieved the loadout and got setPos on the Position.


We tried both Parameter settings, nether of which seemed to have stopped the issue, therefore we decided to turn off the feature.
https://github.com/PulsarNeutronStar/HeartsAndMinds/commit/1a553e2ac1a33af2ca6f780d1afb15359c66604d

**Add mission file:**
To long ago, dont have it anymore.
Here is the Mission on Github before we disabled the feature.
https://github.com/PulsarNeutronStar/HeartsAndMinds/tree/defc6f413ff1990889e870ccb60900af53d1edde


**RPT log file:**
Cant retrieve .rpt since arma nuked the older .rpt
(We disabled the feature 3 weeks ago - https://github.com/PulsarNeutronStar/HeartsAndMinds/commit/1a553e2ac1a33af2ca6f780d1afb15359c66604d)

server_console.log file to proof to you that non of us is using a cracked version 🙄 
[server_console_7592.txt](https://github.com/Vdauphin/HeartsAndMinds/files/11009314/server_console_7592.txt)

**Comment by Vdauphin** [comment] 2023-03-18 20:09
> If you want i can show you the invoice for it.

In the first place, I just need a ticket with a properly filled template. Sad you didn't do it 3 weeks ago but now we can start to investigate

Can you reproduce the issue with the last 1.23.1? 1.23.0 was for testing and had a bug with ACRE2 (which was messing with the saving slot system during serialisation)
Also, enable debug log in mission parameters so we will have more information when the issue appear 

Ideally with:
```sqf
[format ["_player %1 _key %2", _player, _key], __FILE__, [false, btc_debug_log, false]] call btc_debug_fnc_message;
````
in deserializeState_s.sqf after the `params`

**Comment by PulsarNeutronStar** [comment] 2023-03-19 01:08
> In the first place, I just need a ticket with a properly filled template. Sad you didn't do it 3 weeks ago but now we can start to investigate
Sad you closed the issue immediately without asking for more information 🙄 

I'll add the line, but idk when ill be able to find some people to test it.

The mission itself is based on 1.23.0. I'll need to look if i added 23.1 or not.

**Comment by Vdauphin** [comment] 2023-03-19 11:49
You are not the first player creating issue and remove the template which ask you all the necessary informations
I usually don't close issue when template is not followed but as there was an already ongoing discussion about this topic, I thought it would be better to have then occur in the same place so people can share their experience. As I said, an issue closed can be open at anytime if any of us fill it relevant. Closing an issue is not a dead end especially in this case where there was an ongoing discussion. Sorry if you found that rude but it didn't mean to be

Fixing issue can be a complexe process and I put a lot of effort to found them when playing and dive into user tickets (this is why I do monthly patch). You have good exemples here https://github.com/Vdauphin/HeartsAndMinds/issues?q=is%3Aissue+is%3Aclosed+label%3Abug

**Comment by PulsarNeutronStar** [comment] 2023-03-24 17:49
We did some testing

Here are our actions:

```
We slot in the first 3 slots.
Start:

Zorn Medic (pp2000)
Mimi AR    (RPK)
Kyo SQL    (?)

1.
I change in the 4. Slot

Zorn -> Marksman (MM)
=> Kyo got some random Marksman kit (+pos?)
=> Zorn spawned at the default location with default kit


2. 
Mimi changed into the old Zorn Slot

Mimi -> Medic Slot
Kyo => TP Zorn Pos + Zorn Kit (from initial spawn)


3.
Kyo goes into Mimi's old Slot
Kyo -> AR Slot -> Default Spawn Pos & Kit
Kyo => AR Kit of someone else + Pos


4. 
Zorn -> SQL Slot
Mimi => TP to old Kyo Pos
Mimi => Kit of old Zorn (first slot)


5. 
Mimi -> MM Slot
Mimi => Default Pos+Kit
Zorn => Old MM  Pos+Kit

6.
Kyo -> Medic Slot
Kyo => Old Mimi Medic Kit + Pos

7. 
Zorn -> AR -> Default Spawn Pos & Kit
Mimi => Kyo Kit + Pos (rpk)

8.
Mimi -> SQL Slot 
Mimi => Default Spawn
Zorn => Old SQL Pos + Kit

9. 
Kyo -> MM Slot
Kyo => Default
Mimi -> Old AR Kit+Pos
```

https://youtu.be/YK3f8XbLo04
I started the recording somewhere in the middle

RPT's of server (Server auto rstarted in the middle of testing)
RPT's of each client
[RPT.zip](https://github.com/Vdauphin/HeartsAndMinds/files/11065040/RPT.zip)

**Comment by Vdauphin** [comment] 2023-03-24 20:56
I took a look to the end of the video and look at the same time at the server.rpt:
- Kyoptic connect at 17:21
- And serveur side:
```
17:21:17 (0:14:33) fnc\eh\playerConnected - _this [1.53726e+009,"76561198032266970","Kyoptic",true,6,"1537258639"]
17:21:17 "Deformer: adjusting local objects for 1537258639"
17:21:17 (0:14:33) fnc\slot\deserializeState_s - _player B Alpha 1-1:3 (Kyoptic) REMOTE _key [6374.53,7164.16,0.032959]
```
- But at the same time Mimi get teleported
- And Kyoptic just spawn like the first time he join the game

This `_player B Alpha 1-1:3 (Kyoptic) REMOTE` clearly state that [btc_slot_fnc_deserializeState_s](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/slot/deserializeState_s.sqf#L36) send to Kyoptic computer the new position, loadout etc. But, looks like Mimi is actually receiving the `remoteExecCall`. This mean that at this precise moment Kyoptic caracter is local to Mimi computer.

I am noticing you created groups of caracter in your mission.sqm. In A3, all IA in the same group are local to the actual team leader. I think when a payer join a group, he is first local to the team leader computer (here Mini) and then the created caracter is sent back to the actual player joining (here Kyoptic). 
This explain why Mini get teleported when Kyoptic is joining. Kyoptic is local to Mini so the `remoteExecCall` is sent to the wrong computer.

If this is true, you should be able to fix the issue by just creating a group per player. I will think about a fix if you confirm the issue is gone

(wtf)

**Comment by PulsarNeutronStar** [comment] 2023-03-25 00:02
i would prefer to keep the groups in the way they are, otherwise the slot selection will just needlessly long...

would a simple sleep/CBA_fnc_waitAndExecute work in that context?

**Comment by Vdauphin** [comment] 2023-03-25 10:01
Well, first we need to make sure the issue is coming from this, just use one slot per group for test

**Comment by Vdauphin** [comment] 2023-04-02 08:54
I played this weekend and players didn't notice this isssue when JIP a game with slot sort by group from the screen selection. But, the server didn't require such long mod list (only CBA, ACE and TFAR). May be one of the mod or just a long list of mod trigger this specific bug. 
During loading, a lot of stuff happen, especially with a lot of mods, so the player object locality could stay much longer wrongly define I guess

Did you give a try to #1499?

**Comment by PulsarNeutronStar** [comment] 2023-04-02 22:19
https://www.youtube.com/watch?v=qrvFOWiZI6g
Been a few busy days - we tested it last friday.

**Comment by PulsarNeutronStar** [comment] 2023-04-03 19:41
> So the bug is not there when using different group for each player?
I think it seems so, yes.

**Comment by Vdauphin** [comment] 2023-04-05 16:16
Just testing https://github.com/Vdauphin/HeartsAndMinds/pull/1499 to much sure it has gone and we should be fine

**Comment by PulsarNeutronStar** [comment] 2023-04-08 17:21
i added the #1499 changes to our file, will update once we got to testing

**Comment by PulsarNeutronStar** [comment] 2023-04-11 16:11
We conducted the testing, the issue of the SQL being teleported away has been resolved!

**Comment by Vdauphin** [comment] 2023-04-11 18:59
Oh! Great news! 🎉
Thank you for testing this!

**Closed** 2023-04-11 19:00 UTC
Labels: bug
